### ISSUE TITLE
create a database node for enhanced Distant Reader backend, and initialize the database

### ISSUE THREAD

**Issue by molikd** [ericleasemorgan/reader#12]

**Comment by ECoulter** [comment]
Node is created; Access instructions in slack; ssh keys (those that I have) are added.

**Comment by ericleasemorgan** [comment]
We're going to go a Plan B here. Instead of using a database like MariaDB or Postgress, we will improve our reduce process with something like this:

   * https://github.com/ericleasemorgan/cord-19/blob/master/bin/wrd2sql.sh

and this:

   * https://github.com/ericleasemorgan/cord-19/blob/master/bin/reduce-wrd.sh
