### ISSUE TITLE
public carrels

### ISSUE THREAD

**Issue by ericleasemorgan** [ericleasemorgan/reader#177]
Alas, the public interface study carrels do not seem to show any keywords. Is this by design?

**Comment by dbrower** [comment]
@ericleasemorgan moved this ticket to where all the other tickets are.

**Comment by dbrower** [comment]
I added keywords to the harvest, but there is a problem with uniqueness of keywords. The original code I modeled mine after (reader-carrel/bin/table.sh) pulls the top 5 words used out of the carrel database. The issue is that there may be many words used the same (maximal) number of times, in which case 5 of the maximal words are selected. But sometimes it gives different selections of the 5.

For example, the carrel "eb-02" has 53 words that occur the 10 times (the maximum for this carrel). only 5 of these are selected to be the "keywords". and these 5 are selected seemingly at random.

Other than this, I think keywords are done.
