### ISSUE TITLE
Can't login. User is redirected to orcid on login never gets to distant reader? 

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#188]
Tried to login at distantreader.org clicked through institutional Orcid authentication and was redirected to https://orcid.org/my-orcid on success instead of to distant reader.

**Comment by dbrower** [comment]
This appears to be a bug in the ORCID/Okta integration. One of them never redirects back to the distantreader app. My guess is ORCID doesn't for some reason since when I tried it I ended up on the ORCID page.

A second clue that the redirect never happens is that when I return to distant reader I'm not logged in. So the callback URL was never called. Trying to log in again was then successful.

I verified that the distant reader is supplying a correct callback URL to ORCID in the first place.

**Comment by nkmeyers** [comment]
This just happened to me again - ironically just back buttoning to Institutional login via orcid in the browser and hitting it again seems to throw you right in.  What is up with this? Is it something about the institutional login vs the straight up orcid login ? We should figure out exactly how to replicate it.

**Comment by dbrower** [comment]
@nkmeyers Has signing in using the "Institutional Account" and then viewing the Okta page ever redirected back to the distant reader for you?

I can reproduce the issue when I try using "Institutional Account". Using an email/password on the orcid page works fine for me. I think this is something on the ORCID side. I'll submit a question to them as soon as I am registered on their listserv.

**Comment by dbrower** [comment]
I contacted Orcid support and I think this issue is now resolved.
