### ISSUE TITLE
Banner Image and Photo Credit on distantreader.org

### ISSUE THREAD

**Issue by molikd** [ericleasemorgan/reader#25]
On https://distantreader.org/ Add photo credit to the photo that’s there which is the Round Reading room at the british museum: https://images.app.goo.gl/rq93BxDE5P8pF2nk8

**Comment by nkmeyers** [comment]
Since the distant reader is not affiliated with the Round Reading room we should eventually replace round reading room with a more appropriate banner image? Here are some ideas & I also emailed K Davis for help. 
![swiftdistantreader](https://user-images.githubusercontent.com/3044754/82156906-30b00580-984c-11ea-99a5-2659dd90aec0.png)
![treedrbanner](https://user-images.githubusercontent.com/3044754/82156909-33125f80-984c-11ea-9c81-fe9660b8d30f.png)
![distantreadertelescopebig](https://user-images.githubusercontent.com/3044754/82156910-33aaf600-984c-11ea-8523-543e0d696eac.png)
![distantreaderdraft](https://user-images.githubusercontent.com/3044754/82156911-34438c80-984c-11ea-82a9-4488f7da3662.png)

**Comment by jodischneider** [comment]
I like the bottom 3 more than the top 1, FWIW. Maybe the bottommost one?

**Comment by molikd** [comment]
I like treedrbanner (2), since distant reader is not associated with the Hubble telescope.

**Comment by ericleasemorgan** [comment]
The Reader is also about getting a set of unstructured data as input and then outputting sets of structured data. Turning "chaos" into a "cosmos", so to speak. Yet another way to look at it is, the Reader presents an opportunity to get a large data set and applying some control to it. --ELM

**Comment by molikd** [comment]
Eric, any thoughts about any of these banners? I can quickly put them up at distantreader.org

**Comment by nkmeyers** [comment]
@molikd & @ericleasemorgan - I emailed K Davis about taking our preferred concept and making us a quality graphic, we might give this one a couple weeks - mine are just concepts for taking the pulse of what's a fit for distant reader, but the art on any of them is not really ready for prime time?

**Comment by ericleasemorgan** [comment]
Dave, I like #4 the best -- the one with the mariner and the spy glass. If we need or are expected to change our logo soon, then I advocate we change it with #4.

**Comment by nkmeyers** [comment]
here's a couple new versions of the above banner concepts 
![piratebanner](https://user-images.githubusercontent.com/3044754/83552113-4160ac80-a4d7-11ea-8641-c162d7355bb9.jpg)

realized that the woman with telescope is actually a pirate when she was colorized - maybe not what we're after, so here's an contemporary alternative : 

![telscopereader](https://user-images.githubusercontent.com/3044754/83551986-14ac9500-a4d7-11ea-95c4-cc1ae04cd939.jpg)

**Comment by nkmeyers** [comment]
here are the logo options to go with the new banner for the top left of the distantreader.org and carrels page and maybe more  - @ericleasemorgan can you preference the logo you like most and put that image up  "all the places it needs to go"?   Both logos are in ND blue. One has ND’s official sans serif font (Galaxie Polaris), the other is Gotham Narrow. Very similar - see if you have a preference. Kristina liked varying the text to make Distant thinner - looks more “distant”, and emphasizes that this is a tool for reading. If we’d like them to have the same weight she'll change it up. 


![distant-reader_logo-gn (1)](https://user-images.githubusercontent.com/3044754/83552446-c8158980-a4d7-11ea-92e4-fc95d60b848c.png)
![distant-reader_logo-gp](https://user-images.githubusercontent.com/3044754/83552481-d9f72c80-a4d7-11ea-8009-3a0934a54b45.png)

**Comment by ericleasemorgan** [comment]
'Saved for future reference.

**Comment by molikd** [comment]
I went ahead and updated https://distantreader.org/ homepage. everything looks pretty. closing.

**Comment by nkmeyers** [comment]
@molikd - turns out the vintage art inspired woman/captain with spyglass clearly depicts a pirate when the earring is colorized and the pegleg is visible so we have an preferred alternate banner featuring a contemporary person 
![image](https://user-images.githubusercontent.com/3044754/84163038-0f070000-aa3f-11ea-8cf4-b9e72d9ef6a8.png)

**Comment by molikd** [comment]
I can change it, but wouldn't a peg leg be advocating for the handicapped? On Jun 9, 2020 10:51 AM, Natalie Meyers <notifications@github.com> wrote:
@molikd - turns out the vintage art inspired woman/captain with spyglass clearly depicts a pirate when the earring is colorized and the pegleg is visible so we have an preferred alternate banner featuring a contemporary person
