### ISSUE TITLE
Add provenance/bibliography for carrel contents 

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#50]
Add a way(maybe from reading the content of the input file or job submission info ? 1) to give credit and 2)show citation(s) and /or links for carrel source(s) including their URL targets if they are URLs - what would a “bibliography” of a carrel’s corpora type page look like? Can we build one from job input data alone?

In otherwords we need a way to cite/show what each distantreader job  indexed so people can know and go visit whatever content was the input for a carrel.  There should possibly be a  carrel metadata page (about this carrel?) Possibly would want to point to the metadata/about page  from a Cite-As feature on a carrel pages menu?  #32

**Comment by ericleasemorgan** [comment]
Yep, and again, we can (easily) do this with the Reader Carrrel code: https://github.com/ericleasemorgan/reader-carrels

**Comment by ericleasemorgan** [comment]
This functionality is implemented with a set of scripts:

  * https://github.com/ericleasemorgan/cord-19/blob/master/bin/add-context.pl
  * https://github.com/ericleasemorgan/cord-19/blob/master/bin/make-table.sh
  * https://github.com/ericleasemorgan/cord-19/blob/master/bin/make-directory.pl

Because these steps required a person to evaluate a carrel, these steps are dangerous to automate; after evaluation the person who created a carrel is expected to run these script, thus adding provenance to the carrel, and then publishing it.
