### ISSUE TITLE
al et still show up in reports even though added to stopwords

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#85]
Why are "al" and "et" still showing up in my carrel reports like [this one](https://cord.distantreader.org/carrels/SusceptibilityGender2/) written at ~4:03A June 7  if I [added them to the stopwords file](https://github.com/ericleasemorgan/reader/commit/a614e9cf231a15fd9df72aa04d82236f14b9d7ee) on June 6 at 10:54 PM EDT? 

![image](https://user-images.githubusercontent.com/3044754/83978001-6d62a000-a8d2-11ea-87eb-7cfc3174178d.png)

I think I need help to understand what's reading what stopwords file(s) and when?  Because I want to make "et" and "al" go AWAY from my reports ;) 
![image](https://user-images.githubusercontent.com/3044754/83978177-b5ce8d80-a8d3-11ea-925f-f2d53ac69146.png)
![image](https://user-images.githubusercontent.com/3044754/83978204-e6aec280-a8d3-11ea-995e-c4dee792568b.png)
![image](https://user-images.githubusercontent.com/3044754/83978216-f928fc00-a8d3-11ea-9258-98783f9c6689.png)

**Comment by archaeocharlie** [comment]
@ericleasemorgan is the underlying data for this coming from topic-model.py? If so, it's just using the default English list when doing CountVectorize rather than the [this list](https://github.com/ericleasemorgan/reader/commit/a614e9cf231a15fd9df72aa04d82236f14b9d7ee). It may also be worth considering converting from LDA with sklearn to gensim.

**Comment by ericleasemorgan** [comment]
As I may (or may not) have said previously, merely updating our stop word file will not resolve the stop word issues.

In the Reader, there are many scripts which can exploit stop words. Unfortunately, I was not diligent about their use. Some scripts use an out-of-the box set of stop words. Others, use a stop word list of my own creation.

To resolve our stop word "issue", we need to:

  1. find all scripts which employ stop words
  2. articulate a simple stop word list of our own design
  3. edit each script to use our own stop word list
  4. evaluate the results
  5. if unsatisfied, then go to Step #2

A cool, future feature, will be to enable the creator of a study carrel to supply a stop word list of their own, but that is for the future. 

When it comes to  the topic modeling, yes, Gensim may be a better choice. All tools have advantages and disadvantages. When it came to Gensim, I believe I found it difficult to reverse-engineer the result in order to determine exactly what files denoted what topic. "Software is never done."

'Make sense?

**Comment by nkmeyers** [comment]
Can the stopword list you propose to create in #2 above simply be the one that's already in the reader codebase at: 
https://github.com/ericleasemorgan/reader/blob/master/etc/stopwords.txt ? 

> To resolve our stop word "issue", we need to: 1. find all scripts which employ stop words **_2. articulate a simple stop word list of our own design_** 


Then for scripts which can take a stopword list we work through and update them specifically to point at: 
https://github.com/ericleasemorgan/reader/blob/master/etc/stopwords.txt ? 

my immediate goal is to get "et al" and other stopwords out of the topic modeling viz .

**Comment by ericleasemorgan** [comment]
Yes, it can be that, but I believe it behooves us to evaluate it and/or start anew.

**Comment by ericleasemorgan** [comment]
I believe this is resolved. The topic modeling application (reader/bin/topic-model.py) was using a generic stop word list. I enhanced the application to use our local stop word list (reader/etc/stopwords.txt), and now, when new carrels are created or when older carrels are re-created, things like "et al" should not show up.

**Comment by nkmeyers** [comment]
@ericleasemorgan thanks! we might need to add fig and % to stopwords . . . idk what the thinking is on treating symbols like % as words but it is showing up in the noun wordclouds I think?

**Comment by ericleasemorgan** [comment]
I already added % to the stop word list.
